### ISSUE TITLE
FR: REST API endpoint / read from remote log

### ISSUE THREAD

**Issue by mgaulton** [RedfieldMonk/WinBan#1]
Hey There, 
Looking at your project, it seems close to what I'm looking for.
In my primary linux segment, I use fail2ban extensively but it doesn't have a way to push updates to a Windows machine to update its firewall. Wondering if that might something you could look into?
either parsing the fail2ban.log from a share or accepting calls from python scripts or the like.

Looks like an awesome start, keep it up!

**Comment by RedfieldMonk** [comment]
> Hey There,
> Looking at your project, it seems close to what I'm looking for.
> In my primary linux segment, I use fail2ban extensively but it doesn't have a way to push updates to a Windows machine to update its firewall. Wondering if that might something you could look into?
> either parsing the fail2ban.log from a share or accepting calls from python scripts or the like.
> 
> Looks like an awesome start, keep it up!

Thanks for the kind words. It's not something I thought of doing but
that does seem to be a good idea. If you have powershell installed on
your Linux boxes I do have Manual-Ban.ps1 that accepts an IP address as
an argument. You could scrape the fail2ban logs and Invoke-Command to
the Windows box. Right now that would be the only way but I'll take a
look at it and see if it makes sense.

**Comment by mgaulton** [comment]
I wouldn't mind your script to look at. Ive been trying to figure it out but I'm having more issues setting windows 10 to allow it than writing the scripts  lol

**Comment by mgaulton** [comment]
Oh and I just created a custom action to call powershell from fail2ban. I used snapd to install powershell

**Comment by RedfieldMonk** [comment]
> I wouldn't mind your script to look at. Ive been trying to figure it out but I'm having more issues setting windows 10 to allow it than writing the scripts lol

Which script are you referring to?

**Comment by mgaulton** [comment]
The Manual-Ban.ps1 you mentioned?

**Comment by RedfieldMonk** [comment]
It's in the repo on the main page right under LICENSE.

**Comment by mgaulton** [comment]
ah i missed that, thanks. I made a simple starting point to play with.
`
$workingDir = "C:\Program Files\WinBan\"
$noBlockList = $workingDir + "noBlockList"



#Function
Function ExtractValidIPAddress($String){
    $IPregex=‘(?<Address>((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))’
    If ($String -Match $IPregex) {$Matches.Address}
}



Get-Content -Path v:\fail2ban.log -Tail 1 -Wait | where {if ($_ -match "Ban")  { 
    $line = $_
    #Run function
    $ip = ExtractValidIPAddress $Line
    Write-Output $ip
    if( $ip -contains '127.0.0.1' -or $ip -contains '192.168.2.' ) {
           $match = $true
           Write-Output 'WHITELIST '  $ip
          # break
    }
    if($match -ne $true) {
    Write-Output "BLock" $line
    New-NetFirewallRule -DisplayName WB_$ip -Name WB_$ip -Direction Inbound -RemoteAddress $ip -Action Block -ErrorAction SilentlyContinue
    #"$epochTime,$ip" | Out-File $banList -Append
    
    } 
}                                
}
`
